### ISSUE TITLE
Finalise dataset idea

### ISSUE THREAD

**Issue by ZOulhadj** [Roe-Binary-Bandits/Data-Engineering#11]
As a team, we should figure out the theme of our pipeline as well as datasets that we will be using.

**Comment by Frioo** [comment]
[Related discussion #9](https://github.com/Roe-Binary-Bandits/Data-Engineering/discussions/9)

**Comment by ZOulhadj** [comment]
This can now be closed as we will be using the housing dataset suggested by @Frioo 🙌
