### ISSUE TITLE
Load data into a separate schema/database

### ISSUE THREAD

**Issue by Frioo** [Roe-Binary-Bandits/Data-Engineering#38]
By default the table seems to be created in the public schema of airflow database.

**Comment by Frioo** [comment]
I've already tried writing a DAG for creating a new database and putting the data there, see here:
https://github.com/Roe-Binary-Bandits/Data-Engineering/blob/load-prices-paid/dags/load-prices-paid.py

That has some issues regarding the syntax for conditional creation of a database (can't recreate it either).
Maybe we should try putting the data into a new schema (e.g. `data`) in the airflow database, instead of creating a new one.

**Comment by ZOulhadj** [comment]
I will take a look at this now and hopefully, I can figure out whats going on.

**Comment by ZOulhadj** [comment]
Closing as this has now been resolved! @Frioo
